package com.rainbow.remote.dto

data class RemotePost(
    val id: String,
    val authorFullname: String?,
    val title: String,
    val selftext: String?,
    val subreddit: String,
    val subredditNamePrefixed: String,
    val subredditId: String,
    val ups: Long?,
    val downs: Long?,
    val upvoteRatio: Float?,
    val allAwardings: List<RemoteAward?>?,
    val totalAwardsReceived: Long?,
    val spoiler: Boolean?,
    val numComments: Long?,
    val pinned: Boolean?,
//    val edited: Boolean?,
    val created: Long,
    val createdUtc: Long,
    val over18: Boolean?,
    val locked: Boolean?,
    val hideScore: Boolean?,
    val isOriginalContent: Boolean?,
    val url: String?,
)