name: Package

on: [ push ]

jobs:
  create-windows-installer:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./desktop
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      #      - name: Grant execute permission for gradlew
      #        run: chmod +x gradlew
      - name: Run packageMsi with Gradle Wrapper
        run: gradle packageMsi
      - name: Upload asset
        uses: actions/upload-artifact@v3
        with:
          #          path: ./desktop/build/compose/binaries/main-release/msi/*.msi
          path: ./desktop/build/compose/binaries/main/msi/*.msi
          name: rainbow.msi

  create-macos-installer:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./desktop
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      #      - name: Grant execute permission for gradlew
      #        run: chmod +x gradlew
      - name: Run packageDmg with Gradle Wrapper
        run: gradle packageDmg
      - name: Upload asset
        uses: actions/upload-artifact@v3
        with:
          #          path: ./desktop/build/compose/binaries/main-release/msi/*.msi
          path: ./desktop/build/compose/binaries/main/dmg/*.dmg
          name: rainbow.dmg

  create-linux-installer:
    runs-on: linux-latest
    defaults:
      run:
        working-directory: ./desktop
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      #      - name: Grant execute permission for gradlew
      #        run: chmod +x gradlew
      - name: Run packageDeb with Gradle Wrapper
        run: gradle packageDeb
      - name: Upload asset
        uses: actions/upload-artifact@v3
        with:
          #          path: ./desktop/build/compose/binaries/main-release/msi/*.msi
          path: ./desktop/build/compose/binaries/main/deb/*.deb
          name: rainbow.deb